#-------------------------------
# General Site Settings
title: Harone Jaaved
description: >
  Data Analyst based in Melbourne, Australia. This portfolio highlights projects
  focused on SQL, Python, Power BI, and business impact. Use the links below to
  view my GitHub and LinkedIn.

baseurl: "" # keep blank for username.github.io sites
url: "https://haronejaaved.github.io"

#-------------------------------
# About Section
subtitle: Data <span style="color:#f58506">Analytics</span> Portfolio
location: "Melbourne, Australia"
avatar_image: /img/avatar.jpg

#-------------------------------
# Contact links
linkedin: "https://www.linkedin.com/in/harone-jaaved/"
github: "https://github.com/haronejaaved"
website: "https://haronejaaved.github.io/"

#-------------------------------
# Build settings
markdown: kramdown
permalink: "/:title/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      read_time: true
      share: true
